# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080

# mysql
spring:
  datasource:
    url: jdbc:mysql://113.116.50.185:65521/db_brush?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# redis
  redis:
    host: 113.116.50.185
    port: 65520
    password: linglouyi
    jedis:
      pool:
        max-idle: 8
        max-wait:
    timeout: 5000ms
# 垃圾，并不会打印sql
logging:
  level:
    com.example.demo.dao : debug
